name: Feature request
description: Propose an enhancement or new capability
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: Backwards compatible
        - label: Affects permissions
        - label: Requires kicking users
